name: pinterest
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  font_awesome_flutter: ^10.0.0
  badges: ^2.0.2
  http: ^0.13.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  lottie: ^1.2.2
  url_launcher: ^6.0.20
  permission_handler: ^9.1.0
  path_provider: ^2.0.9
  connectivity_plus: ^2.2.1
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/share_images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #